# path related variables
paths:
  raw_data_directory: "data/raw/"
  raw_training_data_directory: "data/training/raw/"
  raw_val_data_directory: "data/validation/raw/"
  raw_test_data_directory: "data/test/raw/"
  processed_training_data_directory: "data/training/processed/"
  featured_training_data_directory: "data/training/featured/"
  processed_test_data_directory: "data/test/processed/"
  featured_test_data_directory: "data/test/featured/"
  processed_val_data_directory: "data/validation/processed/"
  featured_val_data_directory: "data/validation/featured/"
  merged_training_data_directory: "data/training/merged"
  merged_val_data_directory: "data/validation/merged"
  merged_test_data_directory: "data/test/merged"
  preprocessor_directory: "models/preprocessor/"
  report_directory: "reports/"
  model_directory: "models/"
  env_directory: ".env"
  portfolio_directory: "portfolio.csv"
  state_directory: "state.json"

data:
  timeframe: '1h'
  backdate: 300
  normalization_window: 30
  start_date: '2020-06-01' # taking 250 extra candles to account for null values encountered during feature engineering and rolling window normalization
  begin_train_date: '2020-10-01'
  begin_val_date: '2024-10-01'
  begin_test_date: '2025-04-01'
  end_date: '2025-09-30'
  num_features: 14
  train_val_split: '2024-09-30'
  val_test_split: '2025-03-31'
  exchange: 'binance'
  symbols:
    - 'ETH/USDT'
    - 'BTC/USDT'
    - 'BNB/USDT'
    - 'SOL/USDT'
    - 'ADA/USDT'
    - 'LINK/USDT'
    - 'XRP/USDT'
    - 'LTC/USDT'
    - 'XLM/USDT'

strategy:
  capital: 1000000
  stop_loss_multiple: 3
  take_profit_multiple: 4.5
  stop_loss_portion : 0.8
  take_profit_portion : 0.8
  slippage_cost_fraction : 0.002
  transaction_cost_fraction : 0.001

hyperparameters:
  num_assets: 10
  input_dim: 126
  action_dim: 10
  num_lstm_layers: 1
  hidden_state_dim: 512
  actor_hidden_dim: 64
  critic_hidden_dim: 64
  gamma: 0.99
  gae_lambda: 0.95
  clip_epsilon: 0.2
  value_loss_coef: 0.5
  entropy_loss_coef: 0.1
  seq_len: 84
  mini_batch_size: 32
  rollout_size: 512
  num_epochs: 15
  learning_rate: 0.001
  bound_reward_factor: 0.11